ecomapp/urls.py
from django.urls import path
from .views import *


app_name="ecomapp"
urlpatterns=[
	path("",ClientHomeView.as_view(),name='clienthome'),
	path("add-to-cart/i-<i_id>/",ClientAddToCartView.as_view(),name='clientaddtocart'),
	path("cart/",ClientCartView.as_view(),name='clientcart'),
	path("manage-cart/<ci_id>-<action>/",ClientManageCartView.as_view(),name='clientmanagecart'),
	path("signup/",CustomerSignupView.as_view(),name='customersignup'),
	path("signin/",CustomerSigninView.as_view(),name='customersignin'),
	path("signout/",CustomerSignoutView.as_view(),name='customersignout'),
	path("checkout/",CustomerCheckoutView.as_view(),name='customercheckout'),
	path("emptycart/",CustomerEmptyCartView.as_view(),name='customeremptycart'),





	#admin site urls
	path("admin-home/",AdminHomeView.as_view(),name='adminhome'),
	path("admin-login/",AdminLoginView.as_view(),name='adminlogin'),
	path("admin-logout/",AdminLogoutView.as_view(),name='adminlogout'),
	path("my-admin/order-<int:pk>/detail/",AdminOrderDetailView.as_view(),name='adminorderdetail'),
	path("my-admin/order-<order_id>/make-payment/",AdminMakePaymentView.as_view(),name='adminmakepayment'),
	path("my-admin/order-<order_id>/change-status/",AdminMakeStatusView.as_view(),name='adminchangestatus'),
	path("my-admin/item-create/",AdminItemCreateView.as_view(),name='adminitemcreate'),
	path("my-admin/item/<int:pk>/update/",AdminItemUpdateView.as_view(),name='adminitemupdate'),
	path("my-admin/item-list/",AdminItemListView.as_view(),name='adminitemlist'),




	]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("ecomapp.urls")),

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/clienttemplates/addtocart.html
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


<h3>Product added to cart successfully</h3>
<button class="btn btn-outline-warning"><a href="/"><strong>Continue Shopping</strong></a></button>
<button class="btn btn-outline-Info"><a href="/cart/"><strong>View Cart</strong></a></button>

templates/clienttemplates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'clientcss/navbar.css' %}"> -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->


</head>

<!-- <body class="container"> -->
<!-- 
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSite Logo</a>
    </div>
    <ul class="nav navbar-nav">
      <a href="/">Home</a>
		<a href="{% url 'ecomapp:clientcart' %}">Cart</a>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
       <li><a href="#">Page 2</a></li> 
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'ecomapp:customersignup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'ecomapp:customersignin' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav> -->
  


 <body class="container">
<div>

		<!-- <div id="header">
			<div class="leftbox"> LOGO image </div> -->
		<a href="/">Home</a>
		<a href="{% url 'ecomapp:clientcart' %}">Cart</a>
		<!-- <div class="rightbox"> -->
		{% if request.user.is_authenticated and request.user.customer %}
		<a href="" style="color: red;">{{request.user.username}}</a>
		<a href="{% url 'ecomapp:customersignout' %}">Signout</a>
		{% else %}
		<a href="{% url 'ecomapp:customersignup' %}">SignUp</a>
		<a href="{% url 'ecomapp:customersignin' %}">Signin</a>
		{% endif %}
	</div>
	
	<hr>
	<div class="row">
		<div class="col-md-3">
			<h3>Categories</h3><hr>
			<a href="{% url 'ecomapp:clienthome' %}">All Products</a>
			{% for rc in root_categories %}
			<li>{{rc.title}}</li>
			{% for sc in rc.category_set.all %}
			<li class="ml-3">
				<a href="{% url 'ecomapp:clienthome' %}?cat={{sc.slug}}">{{sc.title}}</a>
			</li>

			{% endfor %}

			{% endfor %}

			
		</div>
		<div class="col-md-9">
			{% block content %}
			{% endblock %}
			
		</div>
		
	</div>

</body>
</html>

templates/clienttemplates/checkout.html
{% extends 'clienttemplates/base.html' %}


{% block content %}


<div class="row">
	<div class="col-md-6">

		<h3>Checkout Form</h3>
		<form action="" method="post" >
			{% csrf_token %}
			{{form.as_p}}
			<button>Place Order</button>
		</form>

		
	</div>
	<div class="col-md-6">
		<h3>Order Summary</h3>
		{% for ci in cart.cartitem_set.all %}
		<div class="row">
			<li>{{ci.item}} {{ci.rate}}*{{ci.quantity}} = {{ci.subtotal}}</li>
		</div>
		{% endfor %}
		<hr>
		<p>Total: Rs. {{cart.total}}</p>
		
	</div>
</div>

{% endblock %}

templates/clienttemplates/clientcart.html
{% extends 'clienttemplates/base.html' %}


{% block content %}

<div class=""row>
	<div class="col-md-12">
		<h3>Cart Items</h3><hr>
		<table class="table">
			<thead>
				<tr>
					<th>SN</th>
					<th>Items</th>
					<th>Rate</th>
					<th>Quantity</th>
					<th>Subtotal</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for ci in cart.cartitem_set.all %}
				<tr>
				<td>{{forloop.counter}}</td>
				<td>{{ci.item.title}}</td>
				<td>{{ci.rate}}</td>
				<td>{{ci.quantity}}</td>
				<td>{{ci.subtotal}}</td>
				<td>
					<a href="{% url 'ecomapp:clientmanagecart' ci.id 'inc' %}" class="btn btn-info"><i class="fa fa-plus"></i></a>
					<a href="{% url 'ecomapp:clientmanagecart' ci.id 'dcr' %}" class="btn btn-warning"><i class="fa fa-minus"></i></a>
					<a href="{% url 'ecomapp:clientmanagecart' ci.id 'rmv' %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
				</td>
				</tr>
				{% endfor %}
				<tr>
					<th colspan="4" class="text-right">
						Total:
					</th>
					<th>{{cart.total}}</th>
				</tr>
			</tbody>
			
		</table>
		{% if cart and cart.cartitem_set.count > 0 %}
		<a href="{% url 'ecomapp:customercheckout' %}" class="pull-right btn btn-info">Checkout</a>
		<a href="{% url 'ecomapp:customeremptycart' %}" class="pull-left btn btn-info">Empty Cart</a>
		{% endif %}
	</div>
	
</div>

{% endblock %}

templates/clienttemplates/customersignin.html
{% extends 'clienttemplates/base.html'%}
{% block content %}
<div class="row">
	<div class="col-md-8 mx-auto">
		<h3>Sign In Form</h3>
		<p>Please sign in for ordering process</p>
		{% if error %}
		<li class="text-danger">{{error}}</li>
		{% endif %}
		<form action="" method="Post" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn btn-info">Signin</button>
			
		</form>
		Don't have an account?<a href="{% url 'ecomapp:customersignup' %}">Signup</a>
			
		
	</div>
</div>



{% endblock %}

templates/clienttemplates/customersignup.html
{% extends 'clienttemplates/base.html'%}
{% block content %}
<div class="row">
	<div class="col-md-8 mx-auto">
		<h3>SignUp Form</h3>
		<p>Please fill the form for ordering process</p>
		<form action="" method="Post" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn btn-info">SignUp</button>
			
		</form>
		Alredy have an account?<a href="{% url 'ecomapp:customersignin' %}">Login</a>
			
		
	</div>
</div>



{% endblock %}

templates/clienttemplates/home.html
{% extends 'clienttemplates/base.html' %}
{% load static %}



{% block content %}

<div class="row ">
	{% for item in all_items %}
	<div class="col-md-3 card shadow ml-3 mb-3">
		<img src="{{item.itemimage_set.first.image.url}}" class="img-fluid" 			alt="Responsive image" style="height: 230px; object-fit: cover">
		<h5>{{item.title}}</h5>
		<p>price:Rs<strike>{{item.mrp}}</strike><br>
				{{item.sp}}
		</p>
		<button class="btn btn-outline-warning font-weight-bold"><a href="{% url 'ecomapp:clientaddtocart' item.id %}"><i class="fa fa-shopping-cart" style="font-size:25px;color:red"></i> Add to Cart</a></button>

	</div>
	
	{% endfor %}
	
</div>


{% endblock %}