ecomapp/urls.py
from django.urls import path
from .views import *


app_name="ecomapp"
urlpatterns=[
	path("",ClientHomeView.as_view(),name='clienthome'),
	path("add-to-cart/i-<i_id>/",ClientAddToCartView.as_view(),name='clientaddtocart'),
	path("cart/",ClientCartView.as_view(),name='clientcart'),
	path("manage-cart/<ci_id>-<action>/",ClientManageCartView.as_view(),name='clientmanagecart'),
	path("signup/",CustomerSignupView.as_view(),name='customersignup'),
	path("signin/",CustomerSigninView.as_view(),name='customersignin'),
	path("signout/",CustomerSignoutView.as_view(),name='customersignout'),
	path("checkout/",CustomerCheckoutView.as_view(),name='customercheckout'),
	path("emptycart/",CustomerEmptyCartView.as_view(),name='customeremptycart'),





	#admin site urls
	path("admin-home/",AdminHomeView.as_view(),name='adminhome'),
	path("admin-login/",AdminLoginView.as_view(),name='adminlogin'),
	path("admin-logout/",AdminLogoutView.as_view(),name='adminlogout'),
	path("my-admin/order-<int:pk>/detail/",AdminOrderDetailView.as_view(),name='adminorderdetail'),
	path("my-admin/order-<order_id>/make-payment/",AdminMakePaymentView.as_view(),name='adminmakepayment'),
	path("my-admin/order-<order_id>/change-status/",AdminMakeStatusView.as_view(),name='adminchangestatus'),
	path("my-admin/item-create/",AdminItemCreateView.as_view(),name='adminitemcreate'),
	path("my-admin/item/<int:pk>/update/",AdminItemUpdateView.as_view(),name='adminitemupdate'),
	path("my-admin/item-list/",AdminItemListView.as_view(),name='adminitemlist'),




	]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("ecomapp.urls")),

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminbase.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<style type="text/css">
		.dropdown {
			position: relative;
			display: inline-block;
		}

		/* Dropdown Content (Hidden by Default) */
		.dropdown-content {
			display: none;
			position: absolute;
			background-color: #f1f1f1;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			z-index: 1;
		}
		.dropdown-content a:hover {
			background-color: #ddd;}

		/* Show the dropdown menu on hover */
		.dropdown:hover .dropdown-content {
			display: block;}

		/* Change the background color of the dropdown button when the dropdown content is shown */
		.dropdown:hover .dropbtn {
			background-color: #3e8e41;}
	</style>

</head>
<body class="container">
	<div>
		<a href="{% url 'ecomapp:adminhome' %}">Home</a>|
		<a href="{% url 'ecomapp:adminitemcreate' %}">Item Create</a>|
		<a href="{% url 'ecomapp:adminitemlist' %}">Item List</a>|


		<div class="dropdown">
			{% if request.user.is_authenticated %}
			<button class="dropbtn">  {{request.user}} </button>
			<div class="dropdown-content">
				<a href="#">  <a href="{% url 'ecomapp:adminlogout' %}">Logout</a></a>
				{% else %}

				<a href="{% url 'ecomapp:adminlogin' %}">Login</a>|
				{% endif %}

			</div>

		</div>
	</div><hr>
	{% block content %}
	
	{% endblock %}
	<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
  
  {% block js %}

  {% endblock %}

</body>
</html>

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% load humanize %}



{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3>Recent Orders</h3><hr>
		<table class="table table-bordered table-hover table-sm">
			<thead>
				<tr>
					<th>SN</th>
					<th>Order Id</th>
					<th>Item Count</th>
					<th>Total amount</th>
					<th>Order By</th>
					<th>Address</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody>
				{% for order in allorders %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td><a href="{% url 'ecomapp:adminorderdetail' order.pk %}">#ORDER_{{order.id}}</a><br>{{order.created_at}}</td>
					<td>{{order.cart.cartitem_set.count }}</td>
					<td>{{order.net_total |intcomma}}/-</td>
					<td>{{order.name}}<br>{{order.cart.customer.user}}</td>
					<td>{{order.street_address}},{{order.district}}<br>{{order.mobile}}</td>
					{% if order.status == 'Delivered' %}
					<td style="color:green">{{order.status}}</td>
					{% elif order.status == 'Canceled'  %}
					<td style="color:red">{{order.status}}</td>
					{% else %}
					<td>{{order.status}}</td>
					{% endif %}
				</tr>
				{% endfor %}
			</tbody>
		</table>
		
	</div>
</div>
{% endblock %}

templates/admintemplates/adminitemcreate.html
{% extends 'admintemplates/adminbase.html' %}



{% block content %}
<u><h2  class="text-center text-info">Item Create Form</h2></u>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-info">Submit Data</button>
</form>

{% endblock %}

templates/admintemplates/adminitemlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% load humanize %}


{% block content %}
<div class="row">
	<div class="col-md-12">
		<u><h3  class="text-center text-info">All Items</h3></u><hr>
		<table class="table table-bordered table-hover table-sm">
			<thead>
				<tr>
					<th>SN</th>
					<th>Category</th>
					<th>Title</th>
					<th>Slug</th>
					<th>Mrp</th>
					<th>SP</th>
					<th>Description</th>
					<th>View Count</th>
					<th>Sale count</th>
					<th>Stock</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for ite in allitems %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{ite.category.title}}</td>
					<td>{{ite.title}}</td>
					<td>{{ite.slug}}</td>
					<td>{{ite.mrp |intcomma}}/-</td>
					<td>{{ite.sp |intcomma}}/-</td>
					<td>{{ite.description | safe|truncatewords:'5'}}</td>
					<td>{{ite.view_count |intcomma}}</td>
					<td>{{ite.sale_count |intcomma}}</td>
					<td>{{ite.stock |intcomma}}</td>
					<td>
						<a href="{% url 'ecomapp:adminitemupdate' ite.id %}" class="btn btn-info btn-sm"> 	<i class="fa fa-check"></i>
						</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

templates/admintemplates/adminlogin.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>


{% block content %}
<div class="row">
	<div class="col-md-4 mx-auto">
		<h3>
			<u><b>Login Form</b></u>
		</h3>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info">Submit</button>
			<span class="text-danger">
				{{error}}
			</span>
			
		</form>
		
	</div>
	
</div>


{% endblock %}

</body>
</html>

templates/admintemplates/adminorderdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load humanize %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3 class="text-center text-info">Order ID: #ORDER_{{order.id}}</h3><hr>
		<div class="row">
			<div class="col-md-6">
				<h4>Customer Information</h4><hr>
				<p style="font-weight: bold;"><span class="text-danger">Order by:</span>{{order.cart.customer}}({{order.cart.customer.user}}</p>
				<p style="font-weight: bold;"><span class="text-danger">Order For:</span>{{order.name}}/ {{order.email}}</p>
				<p style="font-weight: bold;"><span class="text-danger">Shipping Address:</span>{{order.street_address}},{{order.district}}</p>
				<p style="font-weight: bold;"><span class="text-danger">Contact Information:</span>,{{order.mobile}}| {{order.cart.customer.mobile}}</p>

				
				
			</div>
			<div class="col-md-6">
				<h3>Order Information</h3><hr>
				<p style="font-weight: bold;"><span class="text-danger">Order On:</span>
				{{order.created_at}}|{{order.created_at|timesince}} ago</p>
				<p style="font-weight: bold;"><span class="text-danger">Net Total:</span>Rs.
				{{order.net_total|intcomma}}/-</p>
				<p  style="font-weight: bold;"><span class="text-danger"> Payment Status:</span><span id="payment_status">{% if order.payment_status is False %}Not Paid <a class="btn btn-primary" id="mp" href="#" data-href="{% url 'ecomapp:adminmakepayment' order.id %}"> Make Paid</a>{% else %}Paid{% endif %}</span></p>
				<p style="font-weight: bold;"><span class="text-danger">Status:</span><span id="ord_status">{{order.status}}</span></p>
				{% if order.status == 'Delivered' or order.status == 'Canceled' %}
				{% else %}
				<p>
					<select id="order_status">
						<option value="a">Change order status</option>
						<option value="p">Make Processing</option>
						<option value="d">Make Delivered</option>
						<option value="c">Make Canceled</option>
					</select>
				</p>
				{% endif %}
				
			</div>
			<div class="col-md-12">
				<u><h4 class="text-center text-info">Ordered Item</h4></u><hr>
				<table class="table table-bordered table-hover table-sm">
					<thead>
						<tr>
							<th>SN</th>
							<th>Items</th>
							<th>Rate</th>
							<th>Quantity</th>
							<th>Subtotal</th>
							
						</tr>
					</thead>
					<tbody>
						{% for ci in order.cart.cartitem_set.all %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td>{{ci.item.title}}</td>
							<td>{{ci.rate}}</td>
							<td>{{ci.quantity}}</td>
							<td>{{ci.subtotal}}</td>

						</tr>
						{% endfor %}
						<tr>
							<th colspan="4" class="text-right">
								Total:
							</th>
							<th>{{order.cart.total|intcomma}}/-</th>
						</tr>
						<tr>
							<th colspan="4" class="text-right">
								Discount:
							</th>
							<th>{{order.discount|intcomma}}/-</th>
						</tr>
						<tr>
							<th colspan="4" class="text-right">
								Net Total:
							</th>
							<th>{{order.net_total|intcomma}}/-</th>
						</tr>
					</tbody>

				</table>

				
			</div>
		</div>
		
	</div>
</div>

{% endblock %}

{% block js %}
<script >
	$(document).ready(function(){
		$('#mp').on('click',function(event){
			event.preventDefault();
			var url=$(this).attr('data-href')
			$.ajax({
				method:'get',
				url: url,
				data:"",
				success:function(resp){
					// location.reload()
					if(resp.message =="payment success"){
						$('#payment_status').text("Paid")

					}
					else{
						alert(resp.message)
					}

				}
			})
		})
	})
</script>
<script type="text/javascript">
	$('#order_status').on('change', function(event){
		var act = $(this).val();
		var url = "{% url 'ecomapp:adminchangestatus' order.id %}";
			$.ajax({
				method:'get',
				url: url,
				data: {'act': act},
				success:function(resp){
					if(resp.message =="Processing"){
						$('#ord_status').text(resp.message)
					}else if (resp.message =="Delivered" || resp.message=="Canceled"){
						$('#ord_status').text(resp.message);
						$('#order_status').css("display","none");

					}
					else{
						alert("Invalid")
						location.reload()
					}

				
				}
			})
		})
</script>

{% endblock %}